name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 20

      - name: Install MySQL
        run: |
          sudo apt-get update -y
          sudo apt-get install mysql-server -y
          sudo mysql -e "CREATE DATABASE webapp_DB;"
          sudo mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root@1234';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON webapp_DB.* TO 'root'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Build and test
        run: |
          ./mvnw clean install

