name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 20
          distribution: 'temurin'

      - name: Start MySQL service
        run: sudo systemctl start mysql

      - name: Check MySQL socket file
        run: ls -l /var/run/mysqld/mysqld.sock

      - name: Check MySQL status and logs
        run: |
          sudo systemctl status mysql
          cat /var/log/mysql/error.log

      - name: Install MySQL
        run: |
          echo "Before MySQL installation"
          sudo apt-get update -y
          sudo apt-get install mysql-server -y
          echo "After MySQL installation"
          sudo mysql -h 127.0.0.1 -e "CREATE DATABASE webapp_DB;"
          sudo mysql -h 127.0.0.1 -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root@1234';"
          sudo mysql -h 127.0.0.1 -e "GRANT ALL PRIVILEGES ON webapp_DB.* TO 'root'@'localhost';"
          sudo mysql -h 127.0.0.1 -e "FLUSH PRIVILEGES;"
          echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'root@1234';" | sudo mysql


      - name: Build and test
        run: |
          ./mvnw clean install

